model_params:
  seed: 0
  lr_init: !!float 2e-3
  scale_l2: !!float 5e-3
  supervise_behv: True
  scale_behv_recons: 1
  steps_ahead: [1, 2, 3, 4]
  hidden_layer_lst: [64, 16]
  num_epochs: 500
  activation: leakyrelu
  which_behv_dims: [0]
  device: cpu
  contrastive: True
  contrastive_temp: 0.2
  contrastive_label_diff: l1
  contrastive_feature_sim: l2
  contrastive_scale: 0.1
  contrastive_time_scaler: 0.0
  contrastive_num_batch: 64
  use_variation: False
  kl_scale: !!float 1e-5
  dim_l: 8
  dist_hidden_layer_lst: [50]
  batch_size: 32
train_params:
  do_full_inference: True
  data_type: hat
  shuffle_train: True
  wandb: False