model_params:
  seed: 0
  num_states: 2
  transitions: recurrent_only
  dynamics: gaussian
  emissions: gaussian_orthog
  single_subspace: True

train_params:
  method: laplace_em
  variational_posterior: structured_meanfield
  alpha: 0.0
  initialize: True
  num_iters: 50
  wandb: False